// Generates contracts/src/PoonsData.sol from poons-art.js so chain output == preview output.
// Usage: node art/export-sol.js
const fs = require('fs');
const path = require('path');
const A = require('./poons-art.js');

const hex = arr => arr.map(b => b.toString(16).padStart(2, '0')).join('');
const rgb = c => c.slice(1);
const q = s => JSON.stringify(s);
const u16 = v => [v >> 8, v & 255];

// Shapes -> runs of [y, x, len, slot], 4 bytes each.
const shapeBytes = [], offsets = [];
for (const n of A.SHAPE_NAMES) {
  offsets.push(shapeBytes.length / 4);
  const px = A.SHAPES[n];
  for (let i = 0; i < px.length;) {
    const [x, y, s] = px[i];
    let j = i + 1;
    while (j < px.length && px[j][1] === y && px[j][0] === px[j - 1][0] + 1 && px[j][2] === s) j++;
    shapeBytes.push(y, x, j - i, s);
    i = j;
  }
}
offsets.push(shapeBytes.length / 4);
if (A.SHAPE_NAMES.length >= A.NONE) throw new Error('too many shapes');

const paletteBytes = p => { let s = ''; for (let i = 0; i < A.SLOT_COUNT; i++) s += p[i] ? rgb(p[i]) : '000000'; return s; };
const T = A.TRAITS;
const typeVariants = T[0].opts.map(o => o[3]);
const specials = typeVariants.map(v => (v ? A.SPECIALS[v] : null));

let names = '';
T.forEach((t, k) => {
  names += `        ${k ? 'else ' : ''}if (k == ${k}) {\n`;
  t.opts.forEach((o, i) => { names += `            ${i ? 'else ' : ''}if (i == ${i}) return ${q(o[0])};\n`; });
  names += `        }\n`;
});
let specialLabels = '';
specials.forEach((sp, ti) => {
  if (!sp) return;
  specialLabels += `        if (t == ${ti}) {\n`;
  T.forEach((tr, k) => { if (sp.labels[tr.key]) specialLabels += `            if (k == ${k}) return ${q(sp.labels[tr.key])};\n`; });
  specialLabels += `        }\n`;
});

const sol = `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

// GENERATED by art/export-sol.js from art/poons-art.js — do not edit by hand.
// Data accessors are public, so this library is deployed on its own and linked into the renderer:
// it keeps the renderer under the 24 KB contract size limit.
library PoonsData {
    uint256 internal constant TRAIT_COUNT = ${T.length};
    uint256 internal constant SLOT_COUNT = ${A.SLOT_COUNT};
    uint256 internal constant NONE = ${A.NONE};
    uint256 internal constant SLOT_LENS_L = ${A.S.LENS_L};
    uint256 internal constant SLOT_LENS_R = ${A.S.LENS_R};
    uint256 internal constant SLOT_INK = ${A.S.INK};
    uint256 internal constant SLOT_BG_A = ${A.S.BG_A};
    uint256 internal constant SLOT_BG_B = ${A.S.BG_B};
    uint256 internal constant SLOT_GLOW = ${A.S.GLOW};

    // Trait indices
${T.map((t, k) => `    uint256 internal constant T_${t.key.toUpperCase()} = ${k};`).join('\n')}

    // Shape ids
${A.SHAPE_NAMES.map((n, i) => `    uint256 internal constant ${n.toUpperCase()} = ${i};`).join('\n')}

    // Rarity tier floors (score) for Uncommon, Rare, Epic; specials are always Legendary.
    uint256 internal constant TIER_UNCOMMON = ${A.TIER_MIN[1]};
    uint256 internal constant TIER_RARE = ${A.TIER_MIN[2]};
    uint256 internal constant TIER_EPIC = ${A.TIER_MIN[3]};

    /// Runs of [y, x, len, slot]; shape s spans runs [OFFSETS[s], OFFSETS[s+1]).
    bytes internal constant SHAPES = hex"${hex(shapeBytes)}";
    /// uint16 run offsets per shape.
    bytes internal constant OFFSETS = hex"${hex(offsets.flatMap(u16))}";
    /// RGB per palette slot for colours that never change.
    bytes internal constant FIXED = hex"${paletteBytes(A.FIXED)}";
    /// 1024-bit bitmaps (row-major) for the dithered background.
    bytes internal constant GLOW_BITS = hex"${(() => { const o = []; for (let i = 0; i < 1024; i += 8) { let b = 0; for (let j = 0; j < 8; j++) b |= A.GLOW_BITS[i + j] << (7 - j); o.push(b); } return hex(o); })()}";
    bytes internal constant GRAD_BITS = hex"${(() => { const o = []; for (let i = 0; i < 1024; i += 8) { let b = 0; for (let j = 0; j < 8; j++) b |= A.GRAD_BITS[i + j] << (7 - j); o.push(b); } return hex(o); })()}";

${T.map((t, k) => `    // ${t.key}
    bytes internal constant W${k} = hex"${hex(t.opts.flatMap(o => u16(o[1])))}";
    bytes internal constant SL${k} = hex"${hex(t.slots)}";
    bytes internal constant C${k} = hex"${t.slots.length ? t.opts.map(o => o[2].map(rgb).join('')).join('') : ''}";
    bytes internal constant V${k} = hex"${hex(A.VARIANTS[k].flat())}";
    bytes internal constant P${k} = hex"${hex(A.POINTS[k])}";`).join('\n')}

    function shapes() public pure returns (bytes memory) {
        return SHAPES;
    }

    function offsets() public pure returns (bytes memory) {
        return OFFSETS;
    }

    function fixedPalette() public pure returns (bytes memory) {
        return FIXED;
    }

    function glowBits() public pure returns (bytes memory) {
        return GLOW_BITS;
    }

    function gradBits() public pure returns (bytes memory) {
        return GRAD_BITS;
    }

    function weights(uint256 k) public pure returns (bytes memory) {
${T.map((_, k) => `        if (k == ${k}) return W${k};`).join('\n')}
        revert();
    }

    function slots(uint256 k) public pure returns (bytes memory) {
${T.map((_, k) => `        if (k == ${k}) return SL${k};`).join('\n')}
        revert();
    }

    function colors(uint256 k) public pure returns (bytes memory) {
${T.map((_, k) => `        if (k == ${k}) return C${k};`).join('\n')}
        revert();
    }

    /// 4 bytes per option: [a, b, c, flags] (see VARIANTS in poons-art.js).
    function variants(uint256 k) public pure returns (bytes memory) {
${T.map((_, k) => `        if (k == ${k}) return V${k};`).join('\n')}
        revert();
    }

    function points(uint256 k) public pure returns (bytes memory) {
${T.map((_, k) => `        if (k == ${k}) return P${k};`).join('\n')}
        revert();
    }

    /// Full palette override for special types (empty for a regular Poon).
    function specialPalette(uint256 t) public pure returns (bytes memory) {
${specials.map((sp, ti) => sp ? `        if (t == ${ti}) return hex"${paletteBytes(sp.palette)}";` : '').filter(Boolean).join('\n')}
        return "";
    }

    /// Attribute value a special type forces for trait k ("" = keep the rolled trait).
    function specialLabel(uint256 t, uint256 k) public pure returns (string memory) {
${specialLabels}        return "";
    }

    function traitName(uint256 k) public pure returns (string memory) {
${T.map((t, k) => `        if (k == ${k}) return ${q(t.key)};`).join('\n')}
        revert();
    }

    function optionName(uint256 k, uint256 i) public pure returns (string memory) {
${names}        revert();
    }
}
`;
const out = path.join(__dirname, '..', 'contracts', 'src', 'PoonsData.sol');
fs.writeFileSync(out, sol);
console.log(`wrote ${out}: ${A.SHAPE_NAMES.length} shapes, ${shapeBytes.length / 4} runs (${shapeBytes.length} bytes)`);
